version: '3.9'

services:

  api-aerolineas:
    build:
      context: ./api-aerolineas
    container_name: api-aerolineas-container
    env_file:
      - .env

  api-compras:
    build:
      context: ./api-compras
    container_name: api-compras-container
    env_file:
      - .env

  api-destinos:
    build:
      context: ./api-destinos
    container_name: api-destinos-container
    env_file:
      - .env

  api-resenas:
    build:
      context: ./api-resenas
    container_name: api-resenas-container
    env_file:
      - .env

  api-usuarios:
    build:
      context: ./api-usuarios
    container_name: api-usuarios-container
    env_file:
      - .env

  api-vuelos:
    build:
      context: ./api-vuelos
    container_name: api-vuelos-container
    env_file:
      - .env