version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword 
      MYSQL_DATABASE: gestion_vuelos   
      MYSQL_USER: myuser                
      MYSQL_PASSWORD: mypassword       
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data:
